keys:
  - hosts:
    - &TRONC age1hswc5xh8dp9zjxer682g4q6h8m4apkk3ry5rl2g3g9ksf7tgrqcqmzem8h
  - users:
    - &celeri age1jymx0uxq6j5zjyc8jsgvha9gmujfgj6t2mv48ffh2vgyc4fq3fnq8c5j0d
creation_rules:
  - path_regex: secrets/hosts/common/.+$
    key_groups:
      - age:
          - *TRONC
          - *celeri
  - path_regex: secrets/hosts/TRONC/.+$
    key_groups:
      - age:
           - *TRONC
           - *celeri
  - path_regex: secrets/users/celeri/.+$
    key_groups:
      - age:
          - *celeri
