keys:
  - hosts:
    - &TRONC age16uqu7zcdzut632whc3lk45x8esgcxznkl9a7maaurgdn8cnmhdxqcyeqku
    - &CIME age1dvar5pl53de5vwjxkppxjeyj8hdnlrc33qwalv05552av8yr5gnq654wqr
  - users:
    - &celeri age1jymx0uxq6j5zjyc8jsgvha9gmujfgj6t2mv48ffh2vgyc4fq3fnq8c5j0d
creation_rules:
  - path_regex: secrets/hosts/common/.+$
    key_groups:
      - age:
          - *TRONC
          - *CIME
          - *celeri
  - path_regex: secrets/users/celeri/.+$
    key_groups:
      - age:
          - *celeri
