# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-7a4f1e9f-ebfc-469f-8d7a-b20dea492540";
    fsType = "btrfs";
  };

  boot.initrd.systemd.enable = true;
  boot.initrd.luks.devices."luks-7a4f1e9f-ebfc-469f-8d7a-b20dea492540" = {
    device = "/dev/disk/by-uuid/7a4f1e9f-ebfc-469f-8d7a-b20dea492540";
    crypttabExtraOpts = [ "tpm1-device=auto" ];
  };

  fileSystems."/home" = {
    device = "/dev/mapper/luks-7a4f1e9f-ebfc-469f-8d7a-b20dea492540";
    fsType = "btrfs";
    options = [ "subvol=home" ];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/luks-7a4f1e9f-ebfc-469f-8d7a-b20dea492540";
    fsType = "btrfs";
    options = [ "subvol=nix" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/2413-2D41";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
